api:
  dockerfile: Dockerfile-api
  build: ./
  ports:
    - "8000"
  links:
    - db
  environment:
    PORT: "8000"
    SECRET: "foobar"
    DATABASE_URL: "postgres://postgres:password@db/db"
    ENVIRONMENT: "development"
    BASE_URL: '/api'
  volumes:
    - ./api:/opt/app
    - ./common:/opt/common
auth:
  dockerfile: Dockerfile-auth
  build: ./
  ports:
    - "8000"
  links:
    - db
  environment:
    PORT: "8000"
    SECRET: "foobar"
    DATABASE_URL: "postgres://postgres:password@db/db"
    ENVIRONMENT: "development"
    BASE_URL: '/auth'
  volumes:
    - ./auth:/opt/app
    - ./common:/opt/common
client:
  dockerfile: Dockerfile-client
  build: ./
  ports:
    - "8080"
  environment:
    PORT: "8080"
    BASE_URL: '/'
  volumes:
    - ./client:/opt/app
    - ./common:/opt/common
proxy:
  dockerfile: Dockerfile-proxy
  build: ./
  links:
    - api
    - auth
    - client
  ports:
    - "80:80"
  environment:
    DOCKER_ENABLED: "true"
  volumes:
    - ./proxy:/opt/app
    - ./common:/opt/common
    - ./public:/opt/public
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: "password"
