FROM node:latest

RUN mkdir /opt/app
WORKDIR /opt/app
ENV DOCKER_ENABLED true
ENV PORT 80
ADD proxy /opt/app
ADD public /opt/public
ADD common /opt/common
RUN npm install


EXPOSE "80"
CMD ["npm", "start"]
